apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: message-queue
    component: consumer
    chapter: jobs
    name : consumers
spec: 
  parallelism: 5
  template:
    metadata:
      labels:
        app: message-queue
        component: consumer
        chapter: jobs
    spec:
      containers:
        - name: worker
          image: gcr.io/kuar-demo/kuard-amd64:1
          imagePullPolicy: Always
      restartPolicy: OnFailure