apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
      volumes:
      - name: "kuard-data"
        hostPath:
          path: "/var/lib/kuard"
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        resources:
          requests:
            cpu: "500m"
            memory : "128Mi"
          limits:
            cpu : "1000"
            memory: "256Mi"
        volumeMounts:
          - mounthPath: "/data"
            name: "kuard-data"
        ports:
         - containerPort: 8080
           name: http
           protocol: TCP
