apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloworlddeployment
  labels:
    app: helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        # Paramètre pour image:
        # Pour Google cloud : eu.gcr.io/osoneskub/helloworld
        # Pour Azure : helloworldosones.azurecr.io/helloworld
        # Pour Amazon : bientôt !
        image: eu.gcr.io/osoneskub/helloworld

---
kind: Service
apiVersion: v1
metadata:
  name: helloworldservice
spec:
  type : LoadBalancer
  selector:
    app: helloworld
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80